export const reportRouteListTheme = {
  wrapper: 'p-3 bg-white border border-slate-200 rounded-lg shadow-sm',
  title: 'text-sm font-bold text-slate-800 mb-2',
  titleWrapper: 'flex justify-between items-center text-sm font-bold text-slate-800 mb-2',
  list: 'mt-2 space-y-2',
  row: 'bg-slate-50 border border-slate-200 rounded-lg p-2 flex flex-col',
  rowContainer: 'flex flex-col w-full',
  rowHeader: 'flex items-center justify-between w-full p-1',
  routeTitle: 'font-semibold text-slate-700 text-sm',
  editContainer: 'flex items-center gap-1 h-8',
  editInputWrapper: 'h-7 flex items-center',
  expandedContainer: 'mt-2 p-2 bg-white border-t border-slate-100 rounded-b-lg space-y-2',
  tmcWrapper: 'space-y-1',
  tmcLabel: 'text-[10px] font-bold text-slate-500 uppercase tracking-wider',
  tmcList: 'text-[11px] text-slate-600 bg-slate-50 p-1.5 rounded border border-slate-100',
  dateInputsContainer: 'flex flex-col gap-2',
  dateInputFlex: 'flex gap-1',
  dateInputWrapper: 'flex-1',
  dateLabel: 'block text-[10px] font-semibold text-slate-600 mb-0.5',
  dateRangeLabel: 'block text-[10px] font-semibold text-slate-700',
  rowHeaderWrapper: 'flex justify-between items-center w-full',
  iconContainer: 'flex items-center gap-0.5',
  reorderButtons: 'flex gap-0.5 items-center',
  removeButtonWrapper: 'flex justify-end mt-1',
  loading: 'text-gray-500 text-sm',
  empty: 'text-gray-400 italic text-sm',
  addForm: 'mt-2 p-1.5 bg-gray-50 rounded text-sm',
  error: 'text-red-500 mt-1 text-xs',
  graphChipsWrapper: 'flex flex-wrap items-center gap-1 pt-2 mt-2 border-t border-slate-100',
  graphChipsLabel: 'text-[10px] font-bold text-slate-500 uppercase tracking-wider mr-1',
  graphChip: 'px-1.5 py-0.5 rounded text-[11px] border bg-slate-100 text-slate-500 border-slate-200 hover:bg-slate-200',
  graphChipActive: 'px-1.5 py-0.5 rounded text-[11px] border bg-blue-100 text-blue-700 border-blue-300 hover:bg-blue-200'
};
