with roadnetwork as 
(
select
	lident || '_' || heading as rd,
	lident, 
	heading,
	sum(case when stcc = '1' then total_tonnage else 0 end) as stcc_1_tonnage, 
	sum(case when stcc = '10' then total_tonnage else 0 end) as stcc_10_tonnage, 
	sum(case when stcc = '11' then total_tonnage else 0 end) as stcc_11_tonnage, 
	sum(case when stcc = '13' then total_tonnage else 0 end) as stcc_13_tonnage, 
	sum(case when stcc = '14' then total_tonnage else 0 end) as stcc_14_tonnage, 
	sum(case when stcc = '19' then total_tonnage else 0 end) as stcc_19_tonnage, 
	sum(case when stcc = '20' then total_tonnage else 0 end) as stcc_20_tonnage, 
	sum(case when stcc = '20 2' then total_tonnage else 0 end) as stcc_2002_tonnage, 
	sum(case when stcc = '21' then total_tonnage else 0 end) as stcc_21_tonnage, 
	sum(case when stcc = '22' then total_tonnage else 0 end) as stcc_22_tonnage, 
	sum(case when stcc = '23' then total_tonnage else 0 end) as stcc_23_tonnage, 
	sum(case when stcc = '24' then total_tonnage else 0 end) as stcc_24_tonnage, 
	sum(case when stcc = '25' then total_tonnage else 0 end) as stcc_25_tonnage, 
	sum(case when stcc = '26' then total_tonnage else 0 end) as stcc_26_tonnage, 
	sum(case when stcc = '27' then total_tonnage else 0 end) as stcc_27_tonnage, 
	sum(case when stcc = '28' then total_tonnage else 0 end) as stcc_28_tonnage, 
	sum(case when stcc = '29' then total_tonnage else 0 end) as stcc_29_tonnage, 
	sum(case when stcc = '30' then total_tonnage else 0 end) as stcc_30_tonnage, 
	sum(case when stcc = '31' then total_tonnage else 0 end) as stcc_31_tonnage, 
	sum(case when stcc = '32' then total_tonnage else 0 end) as stcc_32_tonnage, 
	sum(case when stcc = '32 4' then total_tonnage else 0 end) as stcc_3204_tonnage, 
	sum(case when stcc = '33' then total_tonnage else 0 end) as stcc_33_tonnage, 
	sum(case when stcc = '34' then total_tonnage else 0 end) as stcc_34_tonnage, 
	sum(case when stcc = '35' then total_tonnage else 0 end) as stcc_35_tonnage, 
	sum(case when stcc = '36' then total_tonnage else 0 end) as stcc_36_tonnage, 
	sum(case when stcc = '37' then total_tonnage else 0 end) as stcc_37_tonnage, 
	sum(case when stcc = '38' then total_tonnage else 0 end) as stcc_38_tonnage, 
	sum(case when stcc = '39' then total_tonnage else 0 end) as stcc_39_tonnage, 
	sum(case when stcc = '40' then total_tonnage else 0 end) as stcc_40_tonnage, 
	sum(case when stcc = '41' then total_tonnage else 0 end) as stcc_41_tonnage, 
	sum(case when stcc = '42' then total_tonnage else 0 end) as stcc_42_tonnage, 
	sum(case when stcc = '46 1' then total_tonnage else 0 end) as stcc_4601_tonnage, 
	sum(case when stcc = '50' then total_tonnage else 0 end) as stcc_50_tonnage, 
	sum(case when stcc = '50 1' then total_tonnage else 0 end) as stcc_5001_tonnage, 
	sum(case when stcc = '50 19' then total_tonnage else 0 end) as stcc_5019_tonnage, 
	sum(case when stcc = '50 2' then total_tonnage else 0 end) as stcc_5002_tonnage, 
	sum(case when stcc = '8' then total_tonnage else 0 end) as stcc_8_tonnage, 
	sum(case when stcc = '9' then total_tonnage else 0 end) as stcc_9_tonnage,
	sum(case when stcc = '1' then total_value else 0 end) as stcc_1_value,
	sum(case when stcc = '10' then total_value else 0 end) as stcc_10_value,
	sum(case when stcc = '11' then total_value else 0 end) as stcc_11_value,
	sum(case when stcc = '13' then total_value else 0 end) as stcc_13_value,
	sum(case when stcc = '14' then total_value else 0 end) as stcc_14_value,
	sum(case when stcc = '19' then total_value else 0 end) as stcc_19_value,
	sum(case when stcc = '20' then total_value else 0 end) as stcc_20_value,
	sum(case when stcc = '20 2' then total_value else 0 end) as stcc_2002_value,
	sum(case when stcc = '21' then total_value else 0 end) as stcc_21_value,
	sum(case when stcc = '22' then total_value else 0 end) as stcc_22_value,
	sum(case when stcc = '23' then total_value else 0 end) as stcc_23_value,
	sum(case when stcc = '24' then total_value else 0 end) as stcc_24_value,
	sum(case when stcc = '25' then total_value else 0 end) as stcc_25_value,
	sum(case when stcc = '26' then total_value else 0 end) as stcc_26_value,
	sum(case when stcc = '27' then total_value else 0 end) as stcc_27_value,
	sum(case when stcc = '28' then total_value else 0 end) as stcc_28_value,
	sum(case when stcc = '29' then total_value else 0 end) as stcc_29_value,
	sum(case when stcc = '30' then total_value else 0 end) as stcc_30_value,
	sum(case when stcc = '31' then total_value else 0 end) as stcc_31_value,
	sum(case when stcc = '32' then total_value else 0 end) as stcc_32_value,
	sum(case when stcc = '32 4' then total_value else 0 end) as stcc_3204_value,
	sum(case when stcc = '33' then total_value else 0 end) as stcc_33_value,
	sum(case when stcc = '34' then total_value else 0 end) as stcc_34_value,
	sum(case when stcc = '35' then total_value else 0 end) as stcc_35_value,
	sum(case when stcc = '36' then total_value else 0 end) as stcc_36_value,
	sum(case when stcc = '37' then total_value else 0 end) as stcc_37_value,
	sum(case when stcc = '38' then total_value else 0 end) as stcc_38_value,
	sum(case when stcc = '39' then total_value else 0 end) as stcc_39_value,
	sum(case when stcc = '40' then total_value else 0 end) as stcc_40_value,
	sum(case when stcc = '41' then total_value else 0 end) as stcc_41_value,
	sum(case when stcc = '42' then total_value else 0 end) as stcc_42_value,
	sum(case when stcc = '46 1' then total_value else 0 end) as stcc_4601_value,
	sum(case when stcc = '50' then total_value else 0 end) as stcc_50_value,
	sum(case when stcc = '50 1' then total_value else 0 end) as stcc_5001_value,
	sum(case when stcc = '50 19' then total_value else 0 end) as stcc_5019_value,
	sum(case when stcc = '50 2' then total_value else 0 end) as stcc_5002_value,
	sum(case when stcc = '8' then total_value else 0 end) as stcc_8_value,
	sum(case when stcc = '9' then total_value else 0 end) as stcc_9_value,
	count(1),
	wkb_geometry
FROM gis_datasets.s189_v193_transearch_routes_2021_new_commodity_sw
group by 1,2,3,wkb_geometry 
union
SELECT 
	lident || '_' || heading as rd, 
	lident, 
	heading,
	sum(case when stcc = '1' then total_tonnage else 0 end) as stcc_1_tonnage, 
	sum(case when stcc = '10' then total_tonnage else 0 end) as stcc_10_tonnage, 
	sum(case when stcc = '11' then total_tonnage else 0 end) as stcc_11_tonnage, 
	sum(case when stcc = '13' then total_tonnage else 0 end) as stcc_13_tonnage, 
	sum(case when stcc = '14' then total_tonnage else 0 end) as stcc_14_tonnage, 
	sum(case when stcc = '19' then total_tonnage else 0 end) as stcc_19_tonnage, 
	sum(case when stcc = '20' then total_tonnage else 0 end) as stcc_20_tonnage, 
	sum(case when stcc = '20 2' then total_tonnage else 0 end) as stcc_2002_tonnage, 
	sum(case when stcc = '21' then total_tonnage else 0 end) as stcc_21_tonnage, 
	sum(case when stcc = '22' then total_tonnage else 0 end) as stcc_22_tonnage, 
	sum(case when stcc = '23' then total_tonnage else 0 end) as stcc_23_tonnage, 
	sum(case when stcc = '24' then total_tonnage else 0 end) as stcc_24_tonnage, 
	sum(case when stcc = '25' then total_tonnage else 0 end) as stcc_25_tonnage, 
	sum(case when stcc = '26' then total_tonnage else 0 end) as stcc_26_tonnage, 
	sum(case when stcc = '27' then total_tonnage else 0 end) as stcc_27_tonnage, 
	sum(case when stcc = '28' then total_tonnage else 0 end) as stcc_28_tonnage, 
	sum(case when stcc = '29' then total_tonnage else 0 end) as stcc_29_tonnage, 
	sum(case when stcc = '30' then total_tonnage else 0 end) as stcc_30_tonnage, 
	sum(case when stcc = '31' then total_tonnage else 0 end) as stcc_31_tonnage, 
	sum(case when stcc = '32' then total_tonnage else 0 end) as stcc_3204_tonnage, 
	sum(case when stcc = '32 4' then total_tonnage else 0 end) as stcc_3204_tonnage, 
	sum(case when stcc = '33' then total_tonnage else 0 end) as stcc_33_tonnage, 
	sum(case when stcc = '34' then total_tonnage else 0 end) as stcc_34_tonnage, 
	sum(case when stcc = '35' then total_tonnage else 0 end) as stcc_35_tonnage, 
	sum(case when stcc = '36' then total_tonnage else 0 end) as stcc_36_tonnage, 
	sum(case when stcc = '37' then total_tonnage else 0 end) as stcc_37_tonnage, 
	sum(case when stcc = '38' then total_tonnage else 0 end) as stcc_38_tonnage, 
	sum(case when stcc = '39' then total_tonnage else 0 end) as stcc_39_tonnage, 
	sum(case when stcc = '40' then total_tonnage else 0 end) as stcc_40_tonnage, 
	sum(case when stcc = '41' then total_tonnage else 0 end) as stcc_41_tonnage, 
	sum(case when stcc = '42' then total_tonnage else 0 end) as stcc_42_tonnage, 
	sum(case when stcc = '46 1' then total_tonnage else 0 end) as stcc_4601_tonnage, 
	sum(case when stcc = '50' then total_tonnage else 0 end) as stcc_50_tonnage, 
	sum(case when stcc = '50 1' then total_tonnage else 0 end) as stcc_5001_tonnage, 
	sum(case when stcc = '50 19' then total_tonnage else 0 end) as stcc_5019_tonnage, 
	sum(case when stcc = '50 2' then total_tonnage else 0 end) as stcc_5002_tonnage, 
	sum(case when stcc = '8' then total_tonnage else 0 end) as stcc_8_tonnage, 
	sum(case when stcc = '9' then total_tonnage else 0 end) as stcc_9_tonnage,
	sum(case when stcc = '1' then total_value else 0 end) as stcc_1_value,
	sum(case when stcc = '10' then total_value else 0 end) as stcc_10_value,
	sum(case when stcc = '11' then total_value else 0 end) as stcc_11_value,
	sum(case when stcc = '13' then total_value else 0 end) as stcc_13_value,
	sum(case when stcc = '14' then total_value else 0 end) as stcc_14_value,
	sum(case when stcc = '19' then total_value else 0 end) as stcc_19_value,
	sum(case when stcc = '20' then total_value else 0 end) as stcc_20_value,
	sum(case when stcc = '20 2' then total_value else 0 end) as stcc_2002_value,
	sum(case when stcc = '21' then total_value else 0 end) as stcc_21_value,
	sum(case when stcc = '22' then total_value else 0 end) as stcc_22_value,
	sum(case when stcc = '23' then total_value else 0 end) as stcc_23_value,
	sum(case when stcc = '24' then total_value else 0 end) as stcc_24_value,
	sum(case when stcc = '25' then total_value else 0 end) as stcc_25_value,
	sum(case when stcc = '26' then total_value else 0 end) as stcc_26_value,
	sum(case when stcc = '27' then total_value else 0 end) as stcc_27_value,
	sum(case when stcc = '28' then total_value else 0 end) as stcc_28_value,
	sum(case when stcc = '29' then total_value else 0 end) as stcc_29_value,
	sum(case when stcc = '30' then total_value else 0 end) as stcc_30_value,
	sum(case when stcc = '31' then total_value else 0 end) as stcc_31_value,
	sum(case when stcc = '32' then total_value else 0 end) as stcc_3204_value,
	sum(case when stcc = '32 4' then total_value else 0 end) as stcc_3204_value,
	sum(case when stcc = '33' then total_value else 0 end) as stcc_33_value,
	sum(case when stcc = '34' then total_value else 0 end) as stcc_34_value,
	sum(case when stcc = '35' then total_value else 0 end) as stcc_35_value,
	sum(case when stcc = '36' then total_value else 0 end) as stcc_36_value,
	sum(case when stcc = '37' then total_value else 0 end) as stcc_37_value,
	sum(case when stcc = '38' then total_value else 0 end) as stcc_38_value,
	sum(case when stcc = '39' then total_value else 0 end) as stcc_39_value,
	sum(case when stcc = '40' then total_value else 0 end) as stcc_40_value,
	sum(case when stcc = '41' then total_value else 0 end) as stcc_41_value,
	sum(case when stcc = '42' then total_value else 0 end) as stcc_42_value,
	sum(case when stcc = '46 1' then total_value else 0 end) as stcc_4601_value,
	sum(case when stcc = '50' then total_value else 0 end) as stcc_50_value,
	sum(case when stcc = '50 1' then total_value else 0 end) as stcc_5001_value,
	sum(case when stcc = '50 19' then total_value else 0 end) as stcc_5019_value,
	sum(case when stcc = '50 2' then total_value else 0 end) as stcc_5002_value,
	sum(case when stcc = '8' then total_value else 0 end) as stcc_8_value,
	sum(case when stcc = '9' then total_value else 0 end) as stcc_9_value,
	count(1),
	st_reverse(wkb_geometry)
	FROM gis_datasets.s188_v192_transearch_routes_2021_new_commodity_ne
	group by 1,2,3,wkb_geometry
) 

select  row_number() over () as id, * into gis_datasets.transearch_export_test  from roadnetwork


