export const abbreviationToStateName = {
  ak: "Alaska",
  al: "Alabama",
  ar: "Arkansas",
  az: "Arizona",
  ca: "California",
  co: "Colorado",
  ct: "Connecticut",
  dc: "District of Columbia",
  de: "Delaware",
  fl: "Florida",
  ga: "Georgia",
  hi: "Hawaii",
  ia: "Iowa",
  id: "Idaho",
  il: "Illinois",
  in: "Indiana",
  ks: "Kansas",
  ky: "Kentucky",
  la: "Louisiana",
  ma: "Massachusetts",
  md: "Maryland",
  me: "Maine",
  mi: "Michigan",
  mn: "Minnesota",
  mo: "Missouri",
  ms: "Mississippi",
  mt: "Montana",
  nc: "North Carolina",
  nd: "North Dakota",
  ne: "Nebraska",
  nh: "New Hampshire",
  nj: "New Jersey",
  nm: "New Mexico",
  nv: "Nevada",
  ny: "New York",
  oh: "Ohio",
  ok: "Oklahoma",
  or: "Oregon",
  pa: "Pennsylvania",
  ri: "Rhode Island",
  sc: "South Carolina",
  sd: "South Dakota",
  tn: "Tennessee",
  tx: "Texas",
  ut: "Utah",
  va: "Virginia",
  vt: "Vermont",
  wa: "Washington",
  wi: "Wisconsin",
  wv: "West Virginia",
  wy: "Wyoming",
};

export const stateNameToAbbreviation = Object.entries(
  abbreviationToStateName
).reduce((acc, [k, v]) => {
  acc[v] = k;
  return acc;
}, {});

export const stateAbbr2FipsCode = {
  ak: "02",
  al: "01",
  ar: "05",
  as: "60",
  az: "04",
  ca: "06",
  co: "08",
  ct: "09",
  dc: "11",
  de: "10",
  fl: "12",
  ga: "13",
  gu: "66",
  hi: "15",
  ia: "19",
  id: "16",
  il: "17",
  in: "18",
  ks: "20",
  ky: "21",
  la: "22",
  ma: "25",
  md: "24",
  me: "23",
  mi: "26",
  mn: "27",
  mo: "29",
  mp: "69",
  ms: "28",
  mt: "30",
  nc: "37",
  nd: "38",
  ne: "31",
  nh: "33",
  nj: "34",
  nm: "35",
  nv: "32",
  ny: "36",
  oh: "39",
  ok: "40",
  or: "41",
  pa: "42",
  pr: "72",
  ri: "44",
  sc: "45",
  sd: "46",
  tn: "47",
  tx: "48",
  um: "74",
  ut: "49",
  va: "51",
  vi: "78",
  vt: "50",
  wa: "53",
  wi: "55",
  wv: "54",
  wy: "56",
};

export const stateFipsCode2Abbr = Object.entries(stateAbbr2FipsCode).reduce(
  (acc, [k, v]) => {
    acc[v] = k;
    return acc;
  },
  {}
);
